<?php

if (!function_exists('getReportCatalog')) {
    function getReportCatalog(): array
    {
        static $catalog = null;
        if ($catalog !== null) {
            return $catalog;
        }

        $catalog = [
            'income_statement' => [
                'key' => 'income_statement',
                'label' => 'Income Statement',
                'description' => 'Revenue vs. expense detail for a specific month.',
                'href' => 'reports/income_statement.php',
                'icon' => 'fa-chart-line',
                'category' => 'financial',
                'kind' => 'report',
                'meta' => 'Month close',
                'supports' => ['monthly'],
            ],
            'balance_sheet' => [
                'key' => 'balance_sheet',
                'label' => 'Balance Sheet',
                'description' => 'Assets, liabilities, and equity snapshot.',
                'href' => 'reports/balance_sheet.php',
                'icon' => 'fa-scale-balanced',
                'category' => 'financial',
                'kind' => 'report',
                'meta' => 'As-of date',
                'supports' => ['annual'],
            ],
            'cash_flow' => [
                'key' => 'cash_flow',
                'label' => 'Cash Flow Statement',
                'description' => 'Operating, investing, and financing activity overview.',
                'href' => 'reports/cash_flow.php',
                'icon' => 'fa-droplet',
                'category' => 'financial',
                'kind' => 'report',
                'meta' => 'Quarter focus',
                'supports' => ['annual'],
            ],
            'ytd_budget_comparison' => [
                'key' => 'ytd_budget_comparison',
                'label' => 'YTD Budget Comparison',
                'description' => 'Actuals vs. plan across major accounts.',
                'href' => 'reports/ytd_budget_comparison.php',
                'icon' => 'fa-columns',
                'category' => 'financial',
                'kind' => 'report',
                'meta' => 'Variance view',
                'supports' => ['ytd'],
            ],
            'monthly_summary' => [
                'key' => 'monthly_summary',
                'label' => 'Monthly Summary',
                'description' => 'Single-page recap leadership can skim quickly.',
                'href' => 'reports/monthly_summary.php',
                'icon' => 'fa-calendar-alt',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Snapshot',
                'supports' => ['monthly'],
            ],
            'expense_report' => [
                'key' => 'expense_report',
                'label' => 'Expense Detail',
                'description' => 'Line-item expenses for targeted audits.',
                'href' => 'reports/expense_report.php',
                'icon' => 'fa-file-invoice-dollar',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Category drill-down',
                'supports' => ['monthly'],
            ],
            'income_report' => [
                'key' => 'income_report',
                'label' => 'Income Detail',
                'description' => 'Donations, dues, and event revenue trends.',
                'href' => 'reports/income_report.php',
                'icon' => 'fa-dollar-sign',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Source drill-down',
                'supports' => ['monthly'],
            ],
            'sources_uses' => [
                'key' => 'sources_uses',
                'label' => 'Sources & Uses',
                'description' => 'Displays how every incoming dollar is deployed.',
                'href' => 'reports/sources_uses.php',
                'icon' => 'fa-route',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Cash accountability',
                'supports' => ['monthly'],
            ],
            'physical_assets_report' => [
                'key' => 'physical_assets_report',
                'label' => 'Physical Assets',
                'description' => 'Equipment and club property inventory.',
                'href' => 'reports/physical_assets_report.php',
                'icon' => 'fa-boxes',
                'category' => 'assets',
                'kind' => 'report',
                'meta' => 'Insurance ready',
                'supports' => ['annual'],
            ],
            'asset_listing' => [
                'key' => 'asset_listing',
                'label' => 'Asset Listing',
                'description' => 'Filterable list with depreciation checkpoints.',
                'href' => 'reports/asset_listing.php',
                'icon' => 'fa-clipboard-check',
                'category' => 'assets',
                'kind' => 'report',
                'meta' => 'Condition check',
                'supports' => ['annual'],
            ],
            'cash_account_report' => [
                'key' => 'cash_account_report',
                'label' => 'Cash Account Activity',
                'description' => 'Monthly inflow/outflow by bank account.',
                'href' => 'reports/cash_account_report.php',
                'icon' => 'fa-piggy-bank',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Bank rec support',
                'supports' => ['monthly'],
            ],
            'ytd_cash_flow' => [
                'key' => 'ytd_cash_flow',
                'label' => 'YTD Cash Flow',
                'description' => 'Tracks cumulative burn or surplus each year.',
                'href' => 'reports/ytd_cash_flow.php',
                'icon' => 'fa-wave-square',
                'category' => 'assets',
                'kind' => 'report',
                'meta' => 'YTD trending',
                'supports' => ['ytd'],
            ],
            'donor_list' => [
                'key' => 'donor_list',
                'label' => 'Donor List',
                'description' => 'Full roster with contact references.',
                'href' => 'reports/donor_list.php',
                'icon' => 'fa-users',
                'category' => 'donations',
                'kind' => 'report',
                'meta' => 'Stewardship',
                'supports' => ['annual'],
            ],
            'donation_summary' => [
                'key' => 'donation_summary',
                'label' => 'Donation Summary',
                'description' => 'Aggregate totals by campaign or fund.',
                'href' => 'reports/donation_summary.php',
                'icon' => 'fa-chart-pie',
                'category' => 'donations',
                'kind' => 'report',
                'meta' => 'Campaign view',
                'supports' => ['annual'],
            ],
            'donation_receipts' => [
                'key' => 'donation_receipts',
                'label' => 'Donation Receipts',
                'description' => 'Batch-print acknowledgement letters.',
                'href' => 'reports/donation_receipts.php',
                'icon' => 'fa-envelope-open-text',
                'category' => 'donations',
                'kind' => 'report',
                'meta' => 'Ready to mail',
                'supports' => ['annual'],
            ],
            'annual_donor_statement' => [
                'key' => 'annual_donor_statement',
                'label' => 'Annual Donor Statement',
                'description' => 'Single PDF per donor for tax season.',
                'href' => 'reports/annual_donor_statement.php',
                'icon' => 'fa-file-signature',
                'category' => 'donations',
                'kind' => 'report',
                'meta' => 'IRS compliant',
                'supports' => ['annual'],
            ],
            'monthly_income_report' => [
                'key' => 'monthly_income_report',
                'label' => 'Monthly Income Report',
                'description' => 'Highlights income lines during a calendar month.',
                'href' => 'reports/monthly_income_report.php',
                'icon' => 'fa-coins',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Revenue focus',
                'supports' => ['monthly'],
            ],
            'ytd_income_statement' => [
                'key' => 'ytd_income_statement',
                'label' => 'YTD Income Statement',
                'description' => 'Tracks accumulated revenue and expenses.',
                'href' => 'reports/ytd_income_statement.php',
                'icon' => 'fa-calendar-alt',
                'category' => 'financial',
                'kind' => 'report',
                'meta' => 'Through current month',
                'supports' => ['ytd'],
            ],
            'ytd_income_statement_monthly' => [
                'key' => 'ytd_income_statement_monthly',
                'label' => 'YTD Income Statement (Monthly)',
                'description' => 'Displays month-by-month cumulative income.',
                'href' => 'reports/ytd_income_statement_monthly.php',
                'icon' => 'fa-calendar-check',
                'category' => 'financial',
                'kind' => 'report',
                'meta' => 'Trend analysis',
                'supports' => ['ytd'],
            ],
            'ytd_cash_flow_monthly' => [
                'key' => 'ytd_cash_flow_monthly',
                'label' => 'YTD Cash Flow (Monthly)',
                'description' => 'Month-by-month running balance of net cash.',
                'href' => 'reports/ytd_cash_flow_monthly.php',
                'icon' => 'fa-water',
                'category' => 'assets',
                'kind' => 'report',
                'meta' => 'Burn rate',
                'supports' => ['ytd'],
            ],
            'ytd_cash_report' => [
                'key' => 'ytd_cash_report',
                'label' => 'YTD Cash Report',
                'description' => 'Summarizes cash inflow/outflow since January.',
                'href' => 'reports/YTD_cash_report.php',
                'icon' => 'fa-wallet',
                'category' => 'assets',
                'kind' => 'report',
                'meta' => 'Cash focus',
                'supports' => ['ytd'],
            ],
            'ytd_income_report' => [
                'key' => 'ytd_income_report',
                'label' => 'YTD Income Report',
                'description' => 'Income categories aggregated for the year.',
                'href' => 'reports/YTD_income_report.php',
                'icon' => 'fa-hand-holding-usd',
                'category' => 'operational',
                'kind' => 'report',
                'meta' => 'Income tracking',
                'supports' => ['ytd'],
            ],
            'financial_statements_portal' => [
                'key' => 'financial_statements_portal',
                'label' => 'Financial Statements Portal',
                'description' => 'Hub for packaged board-ready statements.',
                'href' => 'reports/financial_statements.php',
                'icon' => 'fa-folder-open',
                'category' => 'financial',
                'kind' => 'portal',
                'meta' => 'Bundles',
                'supports' => ['annual'],
            ],
            'custom_report_builder' => [
                'key' => 'custom_report_builder',
                'label' => 'Custom Report Builder',
                'description' => 'Launch guided wizard to craft a custom export.',
                'href' => 'reports/generate_report.php',
                'icon' => 'fa-plus-circle',
                'category' => 'utility',
                'kind' => 'tool',
                'meta' => 'Ad-hoc',
                'supports' => ['monthly', 'ytd', 'annual'],
            ],
            'report_type_distribution_chart' => [
                'key' => 'report_type_distribution_chart',
                'label' => 'Report Type Distribution',
                'description' => 'Pie chart summarizing generated report mix.',
                'href' => '#reportTypeChart',
                'icon' => 'fa-chart-pie',
                'category' => 'analytics',
                'kind' => 'chart',
                'meta' => 'Visual insight',
                'supports' => ['monthly', 'ytd', 'annual'],
            ],
            'monthly_generation_trend_chart' => [
                'key' => 'monthly_generation_trend_chart',
                'label' => 'Monthly Generation Trend',
                'description' => 'Line chart of 12-month report volume.',
                'href' => '#monthlyReportChart',
                'icon' => 'fa-chart-line',
                'category' => 'analytics',
                'kind' => 'chart',
                'meta' => 'Volume trend',
                'supports' => ['monthly', 'ytd', 'annual'],
            ],
        ];

        return $catalog;
    }
}

if (!function_exists('getReportCatalogForType')) {
    function getReportCatalogForType(string $groupType): array
    {
        $groupType = strtolower(trim($groupType));
        $catalog = getReportCatalog();
        return array_values(array_filter($catalog, static function ($item) use ($groupType) {
            return in_array($groupType, $item['supports'] ?? [], true);
        }));
    }
}

if (!function_exists('getReportCatalogItem')) {
    function getReportCatalogItem(string $key): ?array
    {
        $catalog = getReportCatalog();
        return $catalog[$key] ?? null;
    }
}
